version: '3.9'

services:
  rabbitmq:
    image: rabbitmq:3-management
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  auth-service:
    build:
      context: ./auth-service
    ports:
      - "8085:8085"
    depends_on:
      - postgres
      - rabbitmq
    
  db-service:
    build:
      context: ./db-service
    ports:
      - "8086:8086"
    depends_on:
      - postgres

  email-service:
    build:
      context: ./email-service
    ports:
      - "8087:8087"
    depends_on:
      - postgres
      - rabbitmq

  postgres:
    build:
      context: ./postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    env_file: .env

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "5050:80"
    depends_on:
      - postgres
    env_file: .env